### ISSUE TITLE
No rule to make target 'keychron/k4/rgb/v2:default_ansi'

### ISSUE THREAD

**Issue by FerenczHollander** [ephb/QMK-on-K4V2#1]
When I try to make my keyboard files with this command: `make keychron/k4/rgb/v2:default_ansi`, it gives me this error. When I look at the SonixQMK repo, it seems like the entire k4 folder is gone. Is there a way forward?

**Comment by ephb** [comment]
Hi @FerenczHollander 
It seems someone removed a lot of Keychron models from that repository during a rebase. I doubt this was intentional.
You can use another branch that still has the files intact.

https://github.com/SonixQMK/qmk_firmware/tree/sn32_master/keyboards/keychron/k4/rgb/v2

**Comment by FerenczHollander** [comment]
When I do `git checkout 6e8c961f4d1e3e4fac72955a8eb88eba91504394` to get the latest commit with the folder still there and I try to make it again, it gives me a Segmentation fault (core dumped) error.

**Comment by ephb** [comment]
I will look into it. If you want to get started now use the prebuilt binary with VIA support in the meantime.

**Comment by FerenczHollander** [comment]
I followed the link from step 5, but all the runs are very old and are archived, so Github has disabled the download option.

**Comment by patreekp** [comment]
hi @FerenczHollander, i was having your exact same problem so i've just switched to branch "sn32_master"
`git switch sn32_master`

removed all the folders from \qmk_firmware\keyboards except for the "keychron" one (all those folder was causing return_code: 35584 when compiling)

then launched qmk msys
navigated to my keyboard folder (in my case `cd qmk_firmware/keyboards/keychron/k4/rgb/v2`)
and then finally launched the compile command (in my case `qmk compile -kb keychron/k4/rgb/v2 -km default_ansi` but you might be using the iso keymap so beware)

i hope this could help you

edit: remember to toggle "Use V2 definition" when loading the .json in Via's Design tab

**Comment by FerenczHollander** [comment]
I tried it, but when I run it I get this error:
`Ψ Compiling keymap with make --jobs=1 keychron/k4/rgb/v2:default_ansi


QMK Firmware 0.7.101
WARNING: Some git submodules are out of date or modified.
 Please consider running make git-submodule.

Making keychron/k4/rgb/v2 with keymap default_ansi

arm-none-eabi-gcc.exe (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/keychron/k4/../../../drivers/led/sn32/matrix_sn32f24xx.c                      In file included from ./lib/chibios/os/rt/include/ch.h:95,
                 from c:\users\feren\qmk_firmware\drivers\led\sn32\matrix_sn32f24xx.c:24:
./lib/chibios/os/rt/include/chchecks.h:48:2: error: #error "obsolete or unknown configuration file"
   48 | #error "obsolete or unknown configuration file"
      |  ^~~~~
./lib/chibios/os/rt/include/chchecks.h:53:2: error: #error "CH_CFG_SMP_MODE not defined in chconf.h"
   53 | #error "CH_CFG_SMP_MODE not defined in chconf.h"
      |  ^~~~~
./lib/chibios/os/rt/include/chchecks.h:101:2: error: #error "CH_CFG_USE_TIMESTAMP not defined in chconf.h"
  101 | #error "CH_CFG_USE_TIMESTAMP not defined in chconf.h"
      |  ^~~~~
./lib/chibios/os/rt/include/chchecks.h:203:2: error: #error "CH_CFG_OS_INSTANCE_INIT_HOOK not defined in chconf.h"
  203 | #error "CH_CFG_OS_INSTANCE_INIT_HOOK not defined in chconf.h"
      |  ^~~~~
./lib/chibios/os/rt/include/chchecks.h:207:2: error: #error "CH_CFG_OS_INSTANCE_EXTRA_FIELDS not defined in chconf.h"
  207 | #error "CH_CFG_OS_INSTANCE_EXTRA_FIELDS not defined in chconf.h"

      |  ^~~~~
./lib/chibios/os/rt/include/chchecks.h:259:2: error: #error "CH_CFG_RUNTIME_FAULTS_HOOK not defined in chconf.h"
  259 | #error "CH_CFG_RUNTIME_FAULTS_HOOK not defined in chconf.h"
      |  ^~~~~
In file included from ./lib/chibios/os/rt/include/ch.h:109:
./lib/chibios/os/rt/include/chobjects.h:451:3: error: expected specifier-qualifier-list before 'CH_CFG_OS_INSTANCE_EXTRA_FIELDS'
  451 |   CH_CFG_OS_INSTANCE_EXTRA_FIELDS
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\users\feren\qmk_firmware\drivers\led\sn32\matrix_sn32f24xx.c:25:
./lib/chibios/os/hal/include/hal.h:136:2: error: #error "obsolete or unknown configuration file"
  136 | #error "obsolete or unknown configuration file"
      |  ^~~~~
 [ERRORS]
 |
 |
 |
make[1]: *** [tmk_core/rules.mk:457: .build/obj_keychron_k4_rgb_v2_default_ansi/../../../drivers/led/sn32/matrix_sn32f24xx.o] Error 1
Make finished with errors
make: *** [Makefile:478: keychron/k4/rgb/v2:default_ansi] Error 1`

**Comment by patreekp** [comment]
@FerenczHollander Um, I don't know, maybe a somewhat obvious question but: what about points 2.5 to 2.7? Did they gave u any erorr?

_2.5. Change directory to qmk_firmware `cd qmk_firmware`
2.6. Pull the submodules `make git-submodule`
2.7. Install utilities `util/qmk_install.sh`_

**Comment by FerenczHollander** [comment]
Yes, I did indeed forget to pull the submodules. After repeating the entire process it has finally worked. In case ephb wants to update the guide, what I ended up doing was follow all the steps, but in between steps 2.6 and 2.7, I switched to the sn32_master branch and thereafter deleted all keyboard folders apart from the keychron folder.

**Comment by ephb** [comment]
Thanks for the update.
I will change the guide to mention the correct branch.
But I have to look into why deleting the folders should be necessary at all when building for a specific target.

**Comment by patreekp** [comment]
@ephb this is the bug report that i've found while searching for a fix https://github.com/qmk/qmk_firmware/issues/13416
